### ISSUE TITLE
Why the pipe design?

### ISSUE THREAD

**Issue by piegamesde** [vonal-project/vonal#1]
I'd prefer a simple command to run the launcher (like `dmenu`), and after having launched an application it will exit automatically. Let the distro/wm handle everything else.

**Comment by fxdave** [comment]
It's a web based application, so the a startup requires at least 500ms. In comparison, using this show/hide method is instant.

However, you can use it that way. Write a script like this: 

```bash
electron . -p ./VONALPIPE
echo 'show' > ./VONALPIPE
echo 'quit' > ./VONALPIPE
```

**Comment by piegamesde** [comment]
Damn these startup times of modern applications :(

But I understand your point. May I propose a slightly different design?

- On startup, the app does not create a pipe, but a socket in `XDG_RUNTIME_DIR` to communicate with other instances.
- If the app is already running, starting it again will trigger a `show` using the socket for communication.
- After the menu is shown, the app hides and waits for being activated over the socket. There is an option to exit it immediately for those who want to.

This has the advantage that both functionality works over a common interface and that the user does not have to put text into a pipe manually.

**Comment by fxdave** [comment]
I have to learn it first, but sounds good to me.

**Comment by fxdave** [comment]
I worry about this solution. I don't really know how to implement it well. 
Here is an example:

Process: Does socket file exist?
 - if yes: quit
 - if no: create and show
 
But what will happen if I accidentally kill the software? The socket file will be there and I will unable to start it. 

Waiting example:
Process: Does socket file exist?
 - if yes: send 'show' 
      - if there will be no answer in **t** time: listen the socket and show the GUI
      - if there is an answer: quit
 - if no: create and show


But if I run it twice in **t** time both starts and shows the GUI. 
In addition, with both examples the first startup will be slow. The second will be slower by **t**.
Also it hides the startup logic from the user.

**Comment by piegamesde** [comment]
There are ways to handle program crashes with respect to sockets: <https://stackoverflow.com/questions/42555403/unix-domain-socket-file-not-removed-on-application-crash>. But even your solution should be quite stable, since you can choose `t` to be pretty low as there is no network delay.

**Comment by fxdave** [comment]
May I do it later, but currently I hold this pipe design. I can see its benefits. The user will be able to control the whole app by his keyboard daemon without starting it again. Also if the app hasn't started yet and the user sends 'show,' it would show the GUI because the pipe exists even if the reader isn't.   I use bspwm with sxhkd and it's very convenient to install. Currently it only has `show, hide, quit` but in the future, I will add more controllable options like: `show calculator-vonal-plugin`, and plugins will be able to extend this functionality. 
Yes it could be done with arguments, but that would be harder to implement, and what is better, reading a word from a pipe or running the node, waiting for electron to be initialized and deciding if the application already has an instance. 

But If you do it I would accept your pull request.
